import Head from 'next/head';
import Image from 'next/image';

import Link from 'next/link';
import { useState } from 'react';

/* ICONOS DE REACT */
import { BsFillMoonStarsFill } from 'react-icons/bs';
import Typing from 'public/typing';

/* IMAGENES IMPORTADAS */
import logoGreen from '../../public/logoGreen.svg';
import trabajo1 from '../../public/trabajo1.png';
import trabajo2 from '../../public/trabajo2.png';
import trabajo3 from '../../public/trabajo3.png';
import trabajo4 from '../../public/trabajo4.png';
import arcon from '../../public/arcon.svg';
import arehucas from '../../public/arehucas.svg';
import creyenteBar from '../../public/creyenteBar.svg';
import gohanHouse from '../../public/gohanHouse.svg';
import kiManagement from '../../public/kiManagement.svg';
import myWay from '../../public/myWay.svg';
import newEra from '../../public/newEra.svg';
import wynwood from '../../public/wynwood.svg';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Juan Cruz Olmos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.ico" />
      </Head>
      <main className=" bg-cremita dark:bg-gris-oscuro">
        {/* HERO SECTION + NAVBAR */}
        <section
          id="top"
          className="bg-fondo1 bg-center bg-auto bg-no-repeat min-h-screen md:bg-fondo2 "
        >
          <nav className="py-5 px-10 mb-12 flex justify-between bg-cremita dark:bg-gris-oscuro">
            <Image src={logoGreen} width={75} />
            <ul className="flex items-center">
              <li>
                <Link
                  className=" bg-naranja font-medium text-white px-4 py-2 rounded-md ml-2"
                  href="/proyectoTest"
                >
                  Resume
                </Link>
              </li>
              <li className=" px-2">
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl dark:text-gray-300"
                />
              </li>
            </ul>
          </nav>

          <div className="text-center p-10 pt-[20vh]">
            <h2 className="text-5xl font-bold font-bolton py-2 text-gris-oscuro md:text-6xl dark:text-cremita">
              I'm{' '}
              <span className="text-verde dark:text-naranja">
                <Typing />
              </span>
            </h2>

            <h3 className=" text-2xl py-2 md:mx-auto md:max-w-lg dark:text-gray-300">
              I can help you with your Design, Ad and FrontEnd necessities
              <br></br>
            </h3>
          </div>
          <div className="text-center font-bolton">
            <Link
              className="bg-naranja p-5 rounded-lg font-medium text-xl text-cremita dark:text-gris-oscuro dark:bg-verde"
              href="#"
            >
              Want to work together?
            </Link>
          </div>
          {/*<div className=" relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={deved} layout="fill" objectFit="cover" />
          </div>*/}
        </section>

        {/* 1er BODY */}
        <section id="featuredProjects" className=" py-10 my-10">
          <div className="text-center">
            <h3 className=" text-3xl font-bold dark:text-cremita">
              Featured Projects
            </h3>
          </div>

          <div className="flex flex-col items-center gap-10 p-10 md:flex-row md:flex-wrap md:justify-center">
            <div className="basis-1/4 flex justify-center grayscale hover:grayscale-0 transition ease-in-out delay-150">
              <Link href={'#featuredProjects'}>
                <Image src={trabajo1} width={300} />
              </Link>
            </div>
            <div className="basis-1/4 flex justify-center grayscale hover:grayscale-0 transition ease-in-out delay-150">
              <Link href={'#featuredProjects'}>
                <Image src={trabajo2} width={300} />
              </Link>
            </div>
            <div className="basis-1/4 flex justify-center grayscale hover:grayscale-0 transition ease-in-out delay-150">
              <Link href={'#featuredProjects'}>
                <Image src={trabajo3} width={300} />
              </Link>
            </div>
          </div>

          <div className="text-center p-5">
            <Link
              href={'#featuredProjects'}
              className="border-[3px] p-5 font-semibold border-naranja rounded-3xl text-naranja hover:bg-naranja hover:text-cremita "
            >
              VIEW ALL WORK
            </Link>
          </div>
        </section>

        <hr className=" border-naranja mx-auto w-[50vw]" />

        {/* 2do BODY */}
        <section>
          <div className="flex flex-col py-10 my-10 gap-5 max-w-3xl items-center mx-auto md:flex-row">
            <div className="flex-none">
              <Image src={trabajo4} width={250} className=" rounded-sm" />
            </div>
            <div className="px-5 flex-1 text-center md:text-left">
              <h3 className=" font-bold text-3xl py-1 dark:text-cremita">
                Ad and Design{'<3'}
              </h3>
              <p className=" text-md py-2 leading-8 text-gray-800 dark:text-gray-400">
                I started working as an Executive Accountant in an agency on
                2021, where i made my first projects. Nowadays I'm working as a
                freelance with an agency and 4 brands.
              </p>
              <p className=" text-md py-2 leading-8 text-gray-800 dark:text-gray-400">
                I specialize on <span className="font-semibold">Branding</span>{' '}
                and <span className="font-semibold">Social Media Design</span>.
                I'm getting into the FrontEnd development world as I already
                know{' '}
                <span className="font-semibold">HTML, CSS and JavaScript</span>.
              </p>
            </div>
          </div>
        </section>

        {/* Contacto */}
        <section
          id="contacto"
          className="bg-fondo3 bg-center bg-cover bg-no-repeat min-h-[400px] flex items-center"
        >
          <div className="mx-auto text-center">
            <h2 className="font-bold text-5xl my-10 text-cremita flex-1">
              You have an idea?
            </h2>

            <Link
              href={'#contacto'}
              className="flex-1 px-20 py-3  border text-cremita border-cremita hover:bg-cremita hover:text-naranja hover:font-semibold"
            >
              Let me listen to it
            </Link>
          </div>
        </section>

        {/* Redes sociales */}
        <section className=" min-h-[250px] flex items-center bg-gris-oscuro dark:bg-cremita">
          <div className="mx-auto">
            <h1 className="font-bold text-2xl text-cremita dark:text-gris-oscuro">
              <a href="#footer" className=" cursor-pointer text-verde">
                @itsmejuancruz
              </a>{' '}
              on instagram!
            </h1>
          </div>
        </section>

        {/* Work Gallery */}
        <section
          id="work"
          className="max-w-3xl mx-auto 2xl:max-w-none 2xl:px-5"
        >
          <div className="text-center pt-10 ">
            <h1 className="text-gris-oscuro font-bold text-2xl dark:text-cremita">
              BRANDS I WORKED WITH
            </h1>
          </div>
          <div className="grid content-center grid-cols-4 grid-rows-auto 2xl:grid-cols-8 2xl:min-h-[250px]">
            <div className="col-span-2 md:col-span-1">
              <Link href={'#'}>
                <Image
                  src={arcon}
                  className="brightness-0 hover:brightness-100 transition ease-in-out delay-150 dark:invert dark:hover:invert-0"
                />
              </Link>
            </div>
            <div className="col-span-2 md:col-span-1">
              <Link href={'#'}>
                <Image
                  src={arehucas}
                  className="brightness-0 hover:brightness-100 transition ease-in-out delay-150 dark:invert dark:hover:invert-0"
                />
              </Link>
            </div>
            <div className="col-span-2 md:col-span-1">
              <Link href={'#'}>
                <Image
                  src={creyenteBar}
                  className="brightness-0 hover:brightness-100 transition ease-in-out delay-150 dark:invert dark:hover:invert-0"
                />
              </Link>
            </div>
            <div className="col-span-2 md:col-span-1 ">
              <Link href={'#'}>
                <Image
                  src={gohanHouse}
                  className="brightness-0 hover:brightness-100 transition ease-in-out delay-150 dark:invert dark:hover:invert-0"
                />
              </Link>
            </div>
            <div className="col-span-2 md:col-span-1 ">
              <Link href={'#'}>
                <Image
                  src={kiManagement}
                  className="brightness-0 hover:brightness-100 transition ease-in-out delay-150 dark:invert dark:hover:invert-0"
                />
              </Link>
            </div>
            <div className="col-span-2 md:col-span-1 ">
              <Link href={'#'}>
                <Image
                  src={myWay}
                  className="brightness-0 hover:brightness-100 transition ease-in-out delay-150 dark:invert dark:hover:invert-0"
                />
              </Link>
            </div>
            <div className="col-span-2 md:col-span-1 ">
              <Link href={'#'}>
                <Image
                  src={newEra}
                  className="brightness-0 hover:brightness-100 transition ease-in-out delay-150 dark:invert dark:hover:invert-0"
                />
              </Link>
            </div>
            <div className="col-span-2 md:col-span-1 ">
              <Link href={'#'}>
                <Image
                  src={wynwood}
                  className="brightness-0 hover:brightness-100 transition ease-in-out delay-150 dark:invert dark:hover:invert-0"
                />
              </Link>
            </div>
          </div>
        </section>

        {/* Footer */}
        <section id="footer" className="bg-verde">
          <footer className=" text-cremita p-10 md:flex md:justify-around md:items-start">
            <div className=" mx-2 pb-8 md:pt-0">
              <h3 className="font-bold text-2xl">Navigate the Site</h3>
              <ul>
                <li>
                  <Link
                    href={'#featuredProjects'}
                    className="cursor-pointer text-md font-light text-green-100 hover:font-medium hover:text-cremita"
                  >
                    {' '}
                    Featured Projects
                  </Link>
                </li>
                <li>
                  <Link
                    href={'#work'}
                    className="cursor-pointer text-md font-light text-green-100 hover:font-medium hover:text-cremita"
                  >
                    {' '}
                    Work
                  </Link>
                </li>
                <li>
                  <Link
                    href={'#contacto'}
                    className="cursor-pointer text-md font-light text-green-100 hover:font-medium hover:text-cremita"
                  >
                    {' '}
                    Contact
                  </Link>
                </li>
                <li>
                  <Link
                    href={'#top'}
                    className="cursor-pointer text-md font-light text-green-100 hover:font-medium hover:text-cremita"
                  >
                    {' '}
                    Go back Top
                  </Link>
                </li>
              </ul>
            </div>
            <hr className="border-cremita md:hidden" />
            <div className=" mx-2 pt-5 pb-8 md:pt-0">
              <h3 className="font-bold text-2xl">Let's connect!</h3>
              <h5 className="font-light text-lg">
                Get weekly inspo and updates
              </h5>
              <div className="flex flex-col justify-center gap-1 mt-2">
                <input
                  type="email"
                  className="px-5 py-2 bg-green-100  text-cremita"
                  placeholder="Your email"
                />
                <button
                  type="submit"
                  className="px-5 py-2  border border-cremita hover:bg-cremita hover:text-verde hover:font-semibold"
                >
                  INSPIRE ME
                </button>
              </div>
            </div>
            <hr className="border-cremita md:hidden" />
            <div className="mx-2 text-center flex flex-col py-6 md:pt-0">
              <h3 className="font-bold text-2xl ">
                Your brand can get better!
              </h3>
              <Link
                href={'#footer'}
                className="mt-5 py-2 border border-cremita hover:bg-cremita hover:text-verde hover:font-semibold"
              >
                Let's make it together!
              </Link>
            </div>
          </footer>
          <p className=" text-center font-thin text-green-100">
            © Juan Cruz Olmos 2023. All Rights Reserved
          </p>
        </section>
      </main>
    </div>
  );
}
