import Head from 'next/head';
import Link from 'next/link';
import { useState } from 'react';

export default function ProyectoX() {
  return (
    <div>
      <Head>
        <title>Juan Cruz Olmos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className=" dark:bg-black dark:text-cremita">
          <Link href="/">VOLVER AL MENU</Link>
        </div>
      </main>
    </div>
  );
}
